mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:com/f/springboot/mapper/*.xml
  #指定Mybatis的实体目录
  type-aliases-package: com.f.springboot.pojo

# 配置数据库信息

# 配法1
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

# 配法2(更推荐)
#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/springboot
#      username: root
#      password: root