server:
  port: 81

datasource:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot
  username: root
  password: root

boolean: TRUE                          # TRUE,true,True,FALSE,false，False均可
float: 3.14                            # 6.8523015e+5  #支持科学计数法
int: 123                               # 0b1010_0111_0100_1010_1110  #支持二进制、八进制、十六进制
string: HelloWorld                     # 字符串可以直接书写
string2: "Hello World"                 # 可以使用双引号包裹特殊字符
date: 2018-02-17                       # 日期必须使用yyyy-MM-dd格式
datetime: 2018-02-17T15:02:31+08:00    # 时间和日期之间使用T连接，最后使用+代表时区

subject:
  - Java
  - 前端
  - 大数据
enterprise:
  name: itcast
  age: 16
  subject:
    - Java
    - 前端
    - 大数据
likes1: [sing,dance]                #数组书写缩略格式
likes2:
  - sing
  - dance
users1:                             #对象数组格式一
  - name: Tom
    age: 4
  - name: Jerry
    age: 5
users2:                             #对象数组格式二
  -
    name: Tom
    age: 4
  -
    name: Jerry
    age: 5
users3: [{ name:Tom , age:4 },{ name:Jerry , age:5 }]    #对象数组缩略格式

baseDir: /usr/local/fire
center:
  dataDir: ${baseDir}/data  # 使用${变量名}的形式引用变量
  tmpDir: ${baseDir}/tmp
  logDir: ${baseDir}/log
  msgDir: ${baseDir}/msgDir

